### ISSUE TITLE
Link to MongoDB service broker sample is broken

### ISSUE THREAD

**Issue by cacti77** [spring-cloud/spring-cloud-cloudfoundry-service-broker#1]
I get a 404 when I click on the link in your readme under 'Getting Started' in the sentence: "A sample MongoDB service broker project is available."
- it would be very useful if we could see a sample please. Thanks!

**Comment by scottfrederick** [comment]
@cacti77 I am in the process of setting up that sample repo. It should be available in the next few days.

**Comment by cacti77** [comment]
Ok thanks; that's great! In the meantime please could you tell me what value I should use for the property `springCloudServiceBrokerVersion` in my broker's pom.xml (so I can pull spring-cloud-cloudfoundry-service-broker in as a dependency)? I'm not that familiar with maven; every version number I've tried has resulted in a failed build!

**Comment by scottfrederick** [comment]
The current version is `1.0.0.BUILD-SNAPSHOT`.

You will also need to add the Spring snapshots repo to your pom.xml: 

```
    <repositories>
        <repository>
            <id>spring-snapshots</id>
            <name>Spring Snapshots</name>
            <url>https://repo.spring.io/snapshot/</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
```

**Comment by cacti77** [comment]
Thanks! My build appears to be working now (my pom.xml was missing that `repositories` entry).

**Comment by scottfrederick** [comment]
The sample project has been moved to https://github.com/spring-cloud-samples/cloudfoundry-service-broker.

**Comment by cacti77** [comment]
Thanks for doing that so quickly; I'll start looking at it right away for my own broker...
