### ISSUE TITLE
Catalog.serviceDefinitions should not be null

### ISSUE THREAD

**Issue by klaus-sap** [spring-cloud/spring-cloud-cloudfoundry-service-broker#14]
If org.springframework.cloud.servicebroker.model.Catalog.serviceDefinitions == null, we can't simply add a service definition to the catalog by calling:
catalog..getServiceDefinitions().add(myServiceDefinition);
Could we change the default constructor to:
this.serviceDefinitions = new ArrayList<ServiceDefinition>();

**Comment by scottfrederick** [comment]
Fixed in 85610dc55219391e00b3e8c82d87dab6c5a1aeda.
