### ISSUE TITLE
Support for multiple Cloud Foundry Instances

### ISSUE THREAD

**Issue by spiegela** [spring-cloud/spring-cloud-cloudfoundry-service-broker#15]
I have a geo-distributed service, and have a need to support multiple Cloud Foundry instances.  The service will need to be aware of the Cloud Foundry instance to which its bound, so we will need to include a CF instance identifier as shown in the [service broker API docs](https://docs.cloudfoundry.org/services/supporting-multiple-cf-instances.html).

**Comment by spiegela** [comment]
@scottfrederick 

I've started a branch to support this using the "routing" method referenced above.  Is this something you'd be interested in merging?

I've looked at using the `X-Api-Info-Location` header, which is already supported, but, for my use-case, I need to query the cloud controller as an authenticated user, which mean the foundation admin will need to provide UAA credentials in the configuration.

**Comment by scottfrederick** [comment]
@spiegela Yes, I'd definitely be interested in seeing a pull request for what you are working on. 

The `X-Api-Info-Location` approach is interesting to me also. I will create a separate issue to capture and propagate that field with broker requests if that won't be part of your PR.

**Comment by spiegela** [comment]
Awesome.  I just need to handle the service instance binding controller, and then it'll be ready for review.
