### ISSUE TITLE
Spring fails to instantiate EmptyListSerializer/EmptyMapSerializer in mvc integration tests

### ISSUE THREAD

**Issue by AlixDaLegend** [spring-cloud/spring-cloud-cloudfoundry-service-broker#24]
Hi,

I 've developped my own PostgreSQL Service Broker using the cloud foundry framework (a basic Spring boot web application - The broker works fine in my Cloud Foundry instance).  I'm using the Spring test framework (MockMvc - _org.springframework.spring-test-4.3.2.RELEASE_) to run integration tests. 

**Problem**
When I run tests (that use the CatalogController for instance), Spring is unable to perform the serialization because it fails to create those two beans: EmptyListSerializer and EmptyMapSerialier.  

> org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.servicebroker.model.EmptyListSerializer]: Is the constructor accessible?; nested exception is java.lang.IllegalAccessException: Class org.springframework.beans.BeanUtils can not access a member of class org.springframework.cloud.servicebroker.model.EmptyListSerializer with modifiers "public"
> at org.springframework.beans.BeanUtils.instantiate(BeanUtils.java:83)

This instantiation problem is caused by the fact that those classes are not "_public_" (I don't know if there is a particular reason for that) as shown below :

```
package org.springframework.cloud.servicebroker.model;
...
...
class EmptyMapSerializer extends JsonSerializer<List<?>> {
...
```

Therefore Spring is unable to access their constructors.  

**Temporary solution**
Yet I was able to run the tests by patching those classes in the app source code (I just created/overwrote the spring package, and added _public_ to the classes).  
Do you think that this patch can be integrated in future releases ?

Thank you in advance.

A.

**Comment by scottfrederick** [comment]
Closed via b9abff36f9362b67e64615fdf2b978608d853e0d
