### ISSUE TITLE
Service Plan should be free by default

### ISSUE THREAD

**Issue by s-bortolussi** [spring-cloud/spring-cloud-cloudfoundry-service-broker#25]
Following [service broker api documentation](https://docs.cloudfoundry.org/services/api.html), service plan  should be free by default.

Actual [implementation](https://github.com/spring-cloud/spring-cloud-cloudfoundry-service-broker/blob/master/src/main/java/org/springframework/cloud/servicebroker/model/Plan.java#L60-L67) makes service plan not free by default

```java
	/**
	 * Indicates whether the plan can be limited by the non_basic_services_allowed field in a Cloud Foundry Quota.
	 */
	@JsonSerialize
	@JsonProperty("free")
	private boolean free;
````

**Comment by scottfrederick** [comment]
Completed via https://github.com/orange-cloudfoundry/spring-cloud-cloudfoundry-service-broker/commit/d2246ed6439dbd2627ad44c93f4f2cedfbe2c28a
