### ISSUE TITLE
Support mutiple type of service binding in a single CreateServiceInstanceBindingResponse

### ISSUE THREAD

**Issue by s-bortolussi** [spring-cloud/spring-cloud-cloudfoundry-service-broker#31]
@scottfrederick It seems that actual ```CreateServiceInstanceBindingResponse``` subclasses implementation makes it impossible to return  for instance ```Credentials``` and ```Volume Mount``` in a single ```CreateServiceInstanceBindingResponse```. Is there a reason for that ?
[Service broker api](https://docs.cloudfoundry.org/services/api.html#types-of-binding) does not seem to be so restrictive.

**Comment by scottfrederick** [comment]
@s-bortolussi You are right on that. I interpreted "volume mount" as a third type of binding, along with app (credentials) binding and route binding. But that's not the case, it is just more details that can be included in an app binding. I'll move the volume mount support into `CreateServiceInstanceAppBindingResponse`.

**Comment by s-bortolussi** [comment]
@scottfrederick thanks for your response

**Comment by scottfrederick** [comment]
Fixed in 0433a405b99a7c14f759b9952d45950aca1d86b1

**Comment by s-bortolussi** [comment]
@scottfrederick thanks for your fix.

**Comment by s-bortolussi** [comment]
@scottfrederick Do you have any due date for 1.0.1.RELEASE ?
