### ISSUE TITLE
Release of 1.0.2

### ISSUE THREAD

**Issue by andreaAlkalay** [spring-cloud/spring-cloud-cloudfoundry-service-broker#45]
Hi,

When is the release of 1.0.2 planned for?

Thanks,
Andrea.

**Comment by scottfrederick** [comment]
@andreaAlkalay The release is imminent, likely in the next few days. We are just finishing up testing of some of the new features.

**Comment by andreaAlkalay** [comment]
Hi,

Thanks a lot :)
Is there any chance you would release a beta version we could use until the official release?

Thanks again and have a great day :)
Andrea.

**Comment by scottfrederick** [comment]
Snapshot builds are always available in https://repo.spring.io/libs-snapshot-local. You just need to change your dependency version to `1.0.2.BUILD-SNAPSHOT` and add that repo to your maven or gradle build file. Any testing and feedback you could provide would be appreciated!

**Comment by andreaAlkalay** [comment]
Thank you, you have been a great help ! :)

**Comment by scottfrederick** [comment]
@andreaAlkalay [1.0.2.RELEASE](https://github.com/spring-cloud/spring-cloud-cloudfoundry-service-broker/releases/tag/v1.0.2.RELEASE) is available in Maven Central.
