### ISSUE TITLE
Is 1.0.1.RELEASE published?

### ISSUE THREAD

**Issue by ReneHerrero** [spring-cloud/spring-cloud-cloudfoundry-service-broker#52]
Hi,

Is 1.0.1.RELEASE published anywhere?

Here's where I'm looking: 
https://repo.spring.io/milestone/org/springframework/cloud/spring-cloud-cloudfoundry-service-broker/

Thanks

**Comment by scottfrederick** [comment]
@ReneHerrero Please see the [Release notes](https://github.com/spring-cloud/spring-cloud-cloudfoundry-service-broker/releases/tag/v1.0.1.RELEASE). `1.0.1.RELEASE` is in the Spring Release repo. There are some technical issues publishing to Maven Central that haven't been resolved yet.

**Comment by scottfrederick** [comment]
@ReneHerrero The `1.0.1.RELEASE` and `1.0.2.RELEASE` releases are now available in Maven Central: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.springframework.cloud%22%20AND%20a%3A%22spring-cloud-cloudfoundry-service-broker%22

**Comment by ReneHerrero** [comment]
Awesome!  Appreciate the notice.
